block-kwin-windows:
  block-pip:
    title:
      value: "Picture-in-picture"
      match_type: exact
block-sites:
- example.com
- youtube.com/watch
flatpak-app-networking:
  allow-only: # when allow-only is populated then only these apps are allowed
    - com.spotify.Client
    - org.signal.Signal
    - com.github.marhkb.Pods
  block:
    - com.brave.Browser
networking:
  mode: allow
  schedules:
    schedule1:
      days_allowed: wednesday
      allow_start: 8:30
      allow_end: 15:00
affected-users: [noah]
tightener-config:
  approved-commands:
  - ^config \.block-hosts \+= "[a-zA-Z0-9.]*"$ # config '.block-hosts += "youtube.com"'
  - ^config \.block-flatpak-networking\.apps \+= "[^"']*\.[^"']*\.[^"']*"$ # config '.block-flatpak-networking.apps += "com.google.Chrome"'
  - ^config \.chromium.block-urls \+= "[^"']*"$ # config '.chromium.block-urls += "youtube.com"'
  - ^config \.user-networking\.users\.noah\.mode = "block"$ # config ".user-networking.users.noah.mode = "block""
  - ^group remove noah wheel$

  - ^config \.flatpak-app-networking\.allow-only \-= \["[^"']*\.[^"']*\.[^"']*"\]$ # config .flatpak-app-networking.allow-only -= ["org.signal.Signal"]
  - ^config \.networking\.mode = "block"$