when:
  - schedule:
      monday: 07:00-18:00 # apply rule on mondays between 7:00 (7am) - 18:00 (6pm)
      tuesday-saturday: 00:00-15:27:50 # apply rule on tuesday, wednesday, thursday between midnight (start of day) and 5pm
      # if time is not specified as time to apply then the rule will not be applied
    mode: replace # replace or merge (merge appends lists, but overrides keys like replace)
    rule:
      block-networking: true

kill-gnome-windows:
  - title: "^Picture in picture$"
    class: "^SDSAD$"
kill-plasma-windows:
- description: "Block Picture in Picture"
  title: "^Picture in picture$"
  class: "^chromium$"

tightener:
  delay: 100
  delays:
    - 'idwt group add noah wheel': 10 # set delay to 10 seconds for adding noah to wheel group