
when:
  - schedule:
      monday: 07:00-18:00 # apply rule on mondays between 7:00 (7am) - 18:00 (6pm)
      tuesday-friday: 00:00-17:00 # apply rule on tuesday, wednesday, thursday between midnight (start of day) and 5pm
      # if time is not specified as time to apply then the rule will not be applied
    mode: replace # replace or merge (merge appends lists, but overrides keys)
    rule:
      networking:
        mode: allow
block-kwin-windows:
  block-pip:
    title:
      value: "Picture-in-picture"
      match_type: exact
block-sites:
- example.com
- youtube.com/watch
flatpak-app-networking:
  allow-only: # when allow-only is populated then only these apps are allowed unless blocked specifically down below
    - com.spotify.Client
    - org.signal.Signal
    - com.github.marhkb.Pods
  block:
    - com.brave.Browser
networking:
  mode: allow
  schedules:
    schedule1:
      days_allowed: wednesday
      allow_start: 8:30
      allow_end: 15:00
affected-users: [noah]
delay: 30 # unit is seconds - meaning a delay of 1.5 minutes is used if 90 is the value
tightener-config:
  approved-commands:
  - ^config \.block-hosts \+= "[a-zA-Z0-9.]*"$ # config '.block-hosts += "youtube.com"'
  - ^config \.block-flatpak-networking\.apps \+= "[^"']*\.[^"']*\.[^"']*"$ # config '.block-flatpak-networking.apps += "com.google.Chrome"'
  - ^config \.chromium.block-urls \+= "[^"']*"$ # config '.chromium.block-urls += "youtube.com"'
  - ^config \.user-networking\.users\.noah\.mode = "block"$ # config ".user-networking.users.noah.mode = "block""
  - ^group remove noah wheel$

  - ^config \.flatpak-app-networking\.allow-only \-= \["[^"']*\.[^"']*\.[^"']*"\]$ # config .flatpak-app-networking.allow-only -= ["org.signal.Signal"]
  - ^config \.networking\.mode = "block"$
  - ^make_file_immutable .*$
