kwin-block-windows:
  - class:
      value: "chromium-browser Chromium-browser" # key wmclass
      # whole_window_class: true # key wmclasscomplete
      match_type: exact # key wmclassmatch - exact = 1, substring = 2, regex = 3
    title:
      value: "Picture in picture" # key title
      match_type: exact # key titlematch - exact = 1, substring = 2, regex = 3
    role:
      value: "browser" # key windowrole
      match_type: exact # key windowrolematch - exact = 1, substring = 2, regex = 3
  - class:
      value: "2nd"
      match_type: exact
    title:
      value: "2ndtitl"
      match_type: substring
block-sites:
- example.com
- youtube.com/watch
block-flatpak-networking:
  john:
    - com.brave.Browser
user-networking:
  users:
    john:
      mode: allow
  schedules:
    schedule1:
      days_allowed: wednesday
      time_start: 8:30
      time_end: 15:00
tightener-config:
  approved-commands:
  - ^config \.block-hosts \+= "[a-zA-Z0-9.]*"$ # config '.block-hosts += "youtube.com"'
  - ^config \.block-flatpak-networking\.apps \+= "[^"']*\.[^"']*\.[^"']*"$ # config '.block-flatpak-networking.apps += "com.google.Chrome"'
  - ^config \.chromium.block-urls \+= "[^"']*"$ # config '.chromium.block-urls += "youtube.com"'
  - ^config \.user-networking\.users\.noah\.mode = "block"$ # config ".user-networking.users.noah.mode = "block""
  - ^group remove noah wheel$
